version: "3"
services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - 9042:9042
    volumes:
      - "./cassandra-init.sh:/cassandra-init.sh"
    command: "sh /cassandra-init.sh"
  app:
    build: .
    ports:
      - 8080:8080